---
- name: Install NGINX
  include_role:
    name: nginxinc.nginx
  vars:
    nginx_modules: []
    nginx_logrotate_conf_enable: true

- name: Create default html dir
  tags: nginx
  file:
    name: '/var/www/default'
    state: directory
    owner: 'root'
    group: 'root'

- name: Create default website
  copy:
    src: 'default/'
    dest: '/var/www/default/'
    owner: root
    group: root
  tags: nginx

- name: Configure NGINX Proxies
  template:
    src: 'proxy.conf.j2'
    dest: '/etc/nginx/sites-available/{{ item.key }}'
    owner: root
    group: root
    mode: 0644
  tags: nginx
  with_dict: '{{ nginx_proxies }}'

- name: Deploy nginx default conf
  copy:
    src: 'default.conf'
    dest: '/etc/nginx/sites-available/default'
    owner: root
    group: root
    mode: 0644
  tags: nginx
  notify: reload nginx

- name: Link NGINX default conf
  file:
    src: '/etc/nginx/sites-available/default'
    dest: '/etc/nginx/sites-enabled/default'
    state: link
  tags: nginx
  notify: reload nginx

- name: Link NGINX Proxies
  file:
    src: '/etc/nginx/sites-available/{{ item.key }}'
    dest: '/etc/nginx/sites-enabled/{{ item.key }}'
    state: link
  tags: nginx
  notify: reload nginx
  with_dict: '{{ nginx_proxies }}'

- name: Enable PHP
  service:
    name: php7.3-fpm
    state: started
    enabled: true
  tags: nginx

- name: Enable NGINX
  service:
    name: nginx
    state: started
    enabled: true
  tags: nginx
