---
- name: Create weechat user
  user:
    name: '{{ weechat_username }}'
    create_home: true
    home: '{{ weechat_home }}'

- name: Make ssl creds dir
  file:
    path: '{{ nginx_server_ssl_cert_dir }}'
    state: directory
    mode: 0755

- name: Make systemd units dir
  file:
    owner: root
    path: /usr/lib/systemd/system
    state: directory
    mode: 0755

- name: Make weechat config dir
  file:
    path: '{{ weechat_config_dir }}'
    state: directory
    mode: 0755
    owner: '{{ weechat_username }}'

- name: Make weechat creds dir
  file:
    path: '{{ weechat_relay_creds_dir }}'
    state: directory
    mode: 0755
    owner: '{{ weechat_username }}'
