---
roles:
  - src: cloudalchemy.prometheus
    version: 2.16.3
  - src: cloudalchemy.grafana
    version: 0.18.0
  - src: cloudalchemy.node_exporter
    version: 0.22.0
  - src: cloudalchemy.snmp-exporter
    version: 0.4.12
  - src: nginxinc.nginx
    version: 0.23.2
collections:
  - name: community.general
    version: 3.0.0
  - name: ansible.posix
    version: 1.2.0
