---
- name: Configure Scaleway Instances
  hosts: ams1
  become: true
  roles:
    - common
  tasks:
    - name: 'Include role from tag'
      include_role:
        name: '{{ item }}'
      with_items: '{{ tags }}'
