---
hostname: athena
enable_firewall: true
firewall_ports:
  http:
    port: 80
    proto: tcp
  https:
    port: 443
    proto: tcp
  dns:
    port: 53
    proto: tcp
  dns_udp:
    port: 53
    proto: udp
  prometheus:
    port: 9090
    proto: tcp
sys_packages:
  - wget
  - vim
  - git
  - tmux
  - zsh
  - python-apt
  - python-pip
  - htop
  - nmap
  - atop

ansible_ssh_user: pi
ansible_ssh_pass: raspberry

# NGINX
nginx_hostname: gobut.me
nginx_proxies:
  graphs: localhost:3000
  radarr: 10.0.0.57:7878
  sonarr: 10.0.0.57:8989
