---
- user:
    name: aur_builder

- lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    validate: /usr/sbin/visudo -cf %s
    create: true

- name: Update Packman
  pacman:
    update_cache: true
  when: ansible_distribution == 'ArchLinux'

- name: Install System Packages
  package:
    pkg: '{{ item }}'
    state: latest
  with_items: '{{ sys_packages }}'
