---
- name: Create aur_builder user
  user:
    name: aur_builder

- name: Add aur builder to sudoers
  lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    validate: /usr/sbin/visudo -cf %s
    create: true
    mode: 0600

- name: Install System Packages
  pacman:
    name: '{{ sys_packages }}'
    update_cache: true
    state: present
