---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present
- name: enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
- name: Allow SSH Access
  community.general.ufw:
    rule: allow
    name: OpenSSH
- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    port: '{{ item.value.port }}'
    proto: '{{ item.value.proto }}'
    comment: '{{ item.key }}'
  with_dict: '{{ firewall_ports }}'
