---
- name: 'Setting hostname'
  hostname:
    name: '{{ hostname }}'
  tags: admin

- include: pi.yaml
  when: ansible_distribution == 'Debian'

- include: centos.yaml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: arch.yaml
  when: ansible_distribution == 'ArchLinux'

- name: Setup Firewall
  block:
    - name: Install UFW
      ansible.builtin.package:
        name: ufw
        state: present
    - name: enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Allow SSH Access
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: Allow all access from RFC1918 networks to this host
      community.general.ufw:
        rule: allow
        port: '{{ item.value.port }}'
        proto: '{{ item.value.proto }}'
        comment: '{{ item.key }}'
      with_dict: '{{ firewall_ports }}'
  when: enable_firewall

- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add the user 'butlerx'
  user:
    name: '{{ username }}'
    comment: '{{ real_name }}'
    groups: wheel
    append: true
    state: present
    createhome: true
    shell: /bin/zsh

- name: Set up authorized keys for the deployer user
  authorized_key:
    user: '{{ username }}'
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/' + ssh_key + '.pub') }}"

- name: Disable root login over SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify:
    - restart sshd

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify:
    - restart sshd

- name: 'Set default bash aliases'
  copy:
    src: etc_profile.d_bash_aliases.sh
    dest: /etc/profile.d/bash_aliases.sh
    mode: 0600
  tags: admin

- name: Setup Node exporter
  include_role:
    name: cloudalchemy.node_exporter
  tags: metrics
