---
- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add the user 'butlerx'
  user:
    name: '{{ username }}'
    comment: '{{ real_name }}'
    groups: wheel
    append: true
    state: present
    createhome: true
    shell: /bin/zsh
  register: user_registered

- name: Set up authorized keys for the deployer user
  authorized_key:
    user: '{{ username }}'
    key: '{{ ssh_pub_key }}'

- name: Disable root login over SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify:
    - restart sshd

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify:
    - restart sshd
